### ISSUE TITLE
Installation guide and docs

### ISSUE THREAD

**Issue by JoseCage** [AlexisBRENON/oh-my-zsh-reminder#1]
Hi @AlexisBRENON can you provide a simple guide/doc about the installation and configuration of zsh-reminder?? It looks nice but i need to see how to install and use it correctly. 

Thanks..

**Comment by AlexisBRENON** [comment]
Hi @JoseCage 

To install it, you just have to put clone the repo in ~/.oh-my-zsh/custom/plugins
`git clone <repo address> ~/.oh-my-zsh/custom/plugins/reminder`

Then add `reminder` to the plugin list in your zshrc.

Finally, look at the [taskwarrior](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/taskwarrior) plugin. It's far more complete and writing a hook for the `precmd` signal will achieve quite the same as my plugin.

Kind regards.

**Comment by JoseCage** [comment]
Thanks.. See You..
