### ISSUE TITLE
Certain text renders funny

### ISSUE THREAD

**Issue by snowe2010** [AlexisBRENON/oh-my-zsh-reminder#11]
```
➜ todo shave on saturday
Todo :
  - shave on satun    day
```
not sure what is happening here.

**Comment by snowe2010** [comment]
```
➜ todo testing testing brday
Todo :
  - shave on fn    iday
  - something on anothen     day
  - something something something
  - hiday
  - testing testing testing
  - testing testing day
  - testing testing fn    iday
  - testing testing aday
  - testing testing aaday
  - testing testing aaaday
  - testing testing fffday
  - testing testing fn    day
  - testing testing faday
  - testing testing fbday
  - testing testing fcday
  - testing testing fdday
  - testing testing feday
  - testing testing ffday
  - testing testing fhday
  - testing testing fiday
  - testing testing fmday
  - testing testing fnday
  - testing testing fday
  - testing testing foday
  - testing testing fpday
  - testing testing fqday
  - testing testing fn    day
  - testing testing fsday
  - testing testing satun    day
  - testing testing sn    day
  - testing testing an    day
  - testing testing bn    day
```
seems that `*r` triggers some weird state.

**Comment by snowe2010** [comment]
Ok, I think the regular expression [here](https://github.com/AlexisBRENON/oh-my-zsh-reminder/blob/master/reminder.plugin.zsh#L35) actually needs to be changed to 

```
➜ echo -E "$@" | tr '\n' '\r' | sed -e 's/\\r\\n//g' -e 's/\\r/\\n/g'
```

though I really don't know what this line is supposed to be doing anyway. seems like it turns `\n` into `\r` and then back again.

**Comment by AlexisBRENON** [comment]
Hi.
Good diagnostic, the regular expression seems to match any `r` instead of `\r`.
If I remember well, this allows you to set multiline ToDos (saving them on a single line in the backing file).
Probably the PR #2 will fix this, making it more portable (using `\0` instead of `\r`).
You can start from it, address the comment, and I will merge it.
Thanks.
