### ISSUE TITLE
Running on a time interval

### ISSUE THREAD

**Issue by partounian** [AlexisBRENON/oh-my-zsh-reminder#5]
It would be great to have the tasks display on a timer instead of every prompt. Would you be interested in this feature? I don't have experience writing much zsh, but I could take on the task if interested.

**Comment by AlexisBRENON** [comment]
Hi,
I'm always interested in new features. However, I don't really understand what you want to achieve.
While you don't run any command, tasks stay displayed, and when you run a command, you probably don't want that the tasks are lost in the whole command output, do you? So, do you have any use case to explain what your timer will do ?

Thanks.

**Comment by partounian** [comment]
Wait x minutes, then check for any shell input/output then display it.  Use case it just so I don't see the tasks show up with every command, but every once in a while.

**Comment by AlexisBRENON** [comment]
OK. No problem, feel free to make a contrib.

Kind.

**Comment by partounian** [comment]
Took a shot at this with while or using the watch command on the zsh-add-hook precmd line with no luck so far.

**Comment by AlexisBRENON** [comment]
My idea would be to add some variables `todo_time_interval` and `todo_last_display_time` and enclose the `todo_display()` code in an `if` block checking if the current timestamp (`date +%s`) is greater than `todo_last_display_time + todo_time_interval`.
Then you will probably have to make some changes to make sure that tasks are redisplayed when you add or remove one, whatever the last displayed time.

Hoping it will help you.
