### ISSUE TITLE
task_done will always delete first occurrence of a substring instead of checking for full string

### ISSUE THREAD

**Issue by Kiailandi** [AlexisBRENON/oh-my-zsh-reminder#7]
Hi, this plugin is simply great, but I have a major problem using it.

In the case of two tasks like

- a b c
- a c d

$ task_done a c d 
or even 
$ task_done "a c d" 
command will delete a b c instead of a c d.

I suppose this is because it goes for a start to end check and deletes on first match but it is kinda frustrating as I frequently use todos like "fix a" "fix b" etc.

Is there any way to avoid this? Do I need to use any specific syntax for the task_done command?

**Comment by AlexisBRENON** [comment]
Hi @Kiailandi ,

For the given example `task_done a c d` effectively delete `a b c` instead of `a c d` because only `a` is taken as pattern (shell parsing and co.). However, quoting the pattern `task_done "a c d"` act on the right entry, so there is no problem.

So, can you re-check your example or give a bigger one to illustrate your problem.

Kind,
Alexis.

**Comment by Kiailandi** [comment]
You are right. The "real" case was probably something like:

- keep this list as short as possible
- arrange a meeting

I did `$task_done a` and it removed `keep this list as short as possible` but I suppose this happened because it checks all the first string for matches before moving to the second.

**Comment by AlexisBRENON** [comment]
Hi,

OK. So this issue come from the fact that the `task_done` function is too greedy, removing the first occurence that matches the argument, even if it is at the very end.

Implementing a better policy would be a real cumbersome. IMHO, the best solution is to rely on the completion system of ZSH.
Steps to achieve this:

- [ ] Take a look at the `compdef` function: http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Functions-2
- [ ] Declare the completion context for `task_done` command. This will probably require a bit of work to fix the issue #8 before.

@Kiailandi Do you want to open the PR yourself or are you waiting that I fix it ?

Kind,
Alexis.

**Comment by Kiailandi** [comment]
At the moment I don't really have the time to get into bash and stuff, I'm a mere user. 

I might have the time in the future tho, so I might end up working on it if this is not a priority.

Do you want me to close this for for the time being or shalll I leave it open?

**Comment by AlexisBRENON** [comment]
No problem. Leave it open. I fixed issue #8, I just need to merge (it was easier than expected). So I will try to fix this one tomorrow.
